import React from "react";
import Head from "next/head";
import Link from "next/link";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>OMDB</title>
        <meta name="description" content="Generated by create next app" />
       </Head>
       <nav>
          <Link href="/">
            <a>Inicio | </a>
          </Link>
          <Link href="/Register">
            <a>Registrarse | </a>
          </Link>
          <Link href="/Login">
            <a>Logearse</a>
          </Link>
        </nav>
      <main>{children}</main>
      <footer>footer</footer>
    </div>
  );
}
